set encoding=utf-8
set nocompatible
set wildmenu

syntax on
set autoindent

set number
set relativenumber
nnoremap <C-n> :set rnu!<CR>

set splitright
set splitbelow

set ignorecase
set smartcase
set hlsearch
set incsearch
vnoremap <C-h> :nohlsearch<CR>
nnoremap <C-h> :nohlsearch<CR>

set undofile
set undodir=~/.vim/undo-history

set mouse=a

"python settings
autocmd FileType python setlocal shiftwidth=4 softtabstop=4 expandtab

"keymappings
nnoremap Y y$
" quicker window movement
nnoremap <M-j> <C-w>j
nnoremap <M-k> <C-w>k
nnoremap <M-h> <C-w>h
nnoremap <M-l> <C-w>l

"netrw explorer
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_browse_split = 4
let g:netrw_winsize = 25
let g:netrw_preview = 1

"colorscheme
set background=dark
colorscheme solarized

"ultisnips
let g:UltiSnipsExpandTrigger="<C-s>"
let g:UltiSnipsJumpForwardTrigger="<C-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"

"YouCompleteMe
let g:ycm_autoclose_preview_window_after_insertion = 1
