local function toggle_hl() vim.o.hlsearch = not(vim.o.hlsearch) end
local function toggle_relative() vim.o.relativenumber = not(vim.o.relativenumber) end
local function toggle_list() vim.o.list = not(vim.o.list) end

vim.keymap.set("n", "<leader>e", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "<leader>o", "o<Esc>")
vim.keymap.set("n", "<leader>O", "O<Esc>")
vim.keymap.set("n", "Y", "y$")
vim.keymap.set("n", "y}", "yV}")
vim.keymap.set("n", "y{", "yV{")
vim.keymap.set("n", "d}", "dV}")
vim.keymap.set("n", "d{", "dV{")
vim.keymap.set("n", "c}", "cV}")
vim.keymap.set("n", "c{", "cV{")
vim.keymap.set("n", "<C-h>", toggle_hl)
vim.keymap.set("n", "<C-n>", toggle_relative)
vim.keymap.set("n", "<F6>", toggle_list)
vim.keymap.set("n", "<C-s>", vim.cmd.update)
vim.keymap.set("i", "<C-s>", vim.cmd.update)
vim.keymap.set("n", "<M-j>", "<C-w>j")
vim.keymap.set("n", "<M-k>", "<C-w>k")
vim.keymap.set("n", "<M-h>", "<C-w>h")
vim.keymap.set("n", "<M-l>", "<C-w>l")
vim.keymap.set("n", "gf", ":edit <cfile><CR>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set({"n", "v"}, "<leader>y", [["+y]], {remap = true})
vim.keymap.set("n", "<leader>Y", [["+Y]], {remap = true})
vim.keymap.set("n", "<leader>xx", "<cmd>TroubleToggle<cr>", {silent = true})
vim.keymap.set("n", "<leader>xw", "<cmd>TroubleToggle workspace_diagnostics<cr>", {silent = true})
vim.keymap.set("n", "<leader>xd", "<cmd>TroubleToggle document_diagnostics<cr>", {silent = true})
vim.keymap.set("n", "<leader>xl", "<cmd>TroubleToggle loclist<cr>", {silent = true})
vim.keymap.set("n", "<leader>xq", "<cmd>TroubleToggle quickfix<cr>",  {silent = true})
vim.keymap.set("n", "<F5>", "<cmd>ToggleBackground<CR>")
