# ls aliases
alias ll='ls -lFh'
alias la='ls -AlFh'
alias l='ls -CF'

alias vi=nvim
alias fvi='fzf | xargs nvim'

alias just="just --unstable --chooser='gum choose'"
alias j="just "

alias ssh-kitty="kitty +kitten ssh"

alias select-sink="pactl list short | grep alsa_output | grep -v monitor | cut -f2 | gum choose | xargs pactl set-default-sink"
